In [8]:
import pandas as pd
import matplotlib.pyplot as plt

customer = pd.read_csv("dim_customer.csv")
campaign = pd.read_csv("dim_campaign.csv")
experiment = pd.read_csv("fact_experiment.csv")
cost = pd.read_csv("fact_campaign_cost.csv")

In [9]:
exp = experiment.merge(campaign, on="campaign_id", how="left")
exp = exp.merge(customer, on="customer_id", how="left")

In [10]:
overall = exp["converted"].mean()
print(f"Overall conversion rate: {overall:.2%}")

Overall conversion rate: 11.27%

In [11]:
version_perf = (
    exp.groupby("campaign_version")
    .agg(
        customers=("customer_id", "count"),
        conversions=("converted", "sum"),
        conversion_rate=("converted", "mean")
    )
    .reset_index()
)

display(version_perf)

  campaign_version  customers  conversions  conversion_rate
0          control      20583         2332         0.113297
1             test      20593         2307         0.112028

In [12]:
channel_perf = (
    exp.groupby("channel")
    .agg(
        customers=("customer_id", "count"),
        conversions=("converted", "sum"),
        conversion_rate=("converted", "mean")
    )
    .reset_index()
)

display(channel_perf)

     channel  customers  conversions  conversion_rate
0   cellular      26135         3852         0.147389
1  telephone      15041          787         0.052324

In [13]:
age_perf = (
    exp.groupby("age_group", observed=True)
    .agg(
        customers=("customer_id", "count"),
        conversions=("converted", "sum"),
        conversion_rate=("converted", "mean")
    )
    .reset_index()
)

display(age_perf)

  age_group  customers  conversions  conversion_rate
0     18-25       1665          349         0.209610
1     26-35      14844         1740         0.117219
2     36-45      12839         1092         0.085053
3     46-55       8247          717         0.086941
4       55+       3581          741         0.206925

In [14]:
budget_perf = (
    cost.groupby(["channel", "campaign_version"])
    .agg(
        customers_contacted=("customers_contacted", "sum"),
        conversions=("conversions", "sum"),
        planned_budget=("planned_budget", "sum"),
        actual_spend=("actual_spend", "sum"),
        estimated_revenue=("estimated_contribution", "sum"),
        estimated_profit=("estimated_profit", "sum")
    )
    .reset_index()
)

display(budget_perf)

,channel,campaign_version,customers_contacted,conversions,planned_budget,actual_spend,estimated_revenue,estimated_profit
0,cellular,control,13065,1947,235170,261300,584100,322800
1,cellular,test,13070,1905,287540,326750,571500,244750
2,telephone,control,7518,385,225540,263130,115500,-147630
3,telephone,test,7523,402,285874,338535,120600,-217935